### PR TITLE
Ft/partners

### PR DESCRIPTION
**Pull request by UmutesiMMA**
Responsive partners section

### CODE REVIEW

**Review by AdelineA — CHANGES_REQUESTED** [review]
You did amazing work but you may look at these few things :
1. You may increase the padding between the header and paragraph on the mobile version only, the other version looks perfect.
Ficat

2. You forget  one description, you can check on the screenshot below:
ficat1

figma photo

ficat2

**Comment by UmutesiMMA** [comment]
> You did amazing work but you may look at these few things :
> 
> 1. You may increase the padding between the header and paragraph on the mobile version only, the other version looks perfect.
>    Ficat
> 2. You forget  one description, you can check on the screenshot below:
>    ficat1
> 
> figma photo
> 
> ficat2

I have done the requested changes, you may check now

**Review by gasangw — CHANGES_REQUESTED** [review]
Hi @UmutesiMMA 

# CHANGES REQUIRED 🟢 

- This is the figma template: `There is padding on top and bottom` I have highlighted it for you.

Screenshot (27)

- Below is your design: Kindly add some padding u can use `py-12` on the main `div`;

Screenshot (28)

**Comment by UmutesiMMA** [comment]
> Hi @UmutesiMMA
> 
> # CHANGES REQUIRED 🟢
> * This is the figma template: `There is padding on top and bottom` I have highlighted it for you.
> 
> Screenshot (27)
> 
> * Below is your design: Kindly add some padding u can use `py-12` on the main `div`;
> 
> Screenshot (28)

I have fixed the padding issue. You may check again

**Review by gasangw — APPROVED** [review]
Hi @UmutesiMMA 

## Congratulations ✔️ 
internin-job


_- All is complete feel free to merge this branch to the dev._

**Pull request merged**
